"""System orchestrator for Letters to My Future Self.

The orchestrator ties together the shared database, the event bus and
all agents. It exposes convenience methods used by the CLI to
create letters, schedule delivery, check status and trigger time
progression. Internally the orchestrator dispatches events to
subscribed agents and ensures that time‑based triggers are evaluated
via the Chrono agent.
"""

from __future__ import annotations

from typing import List, Optional

from .memory.db import Database
from .events.event_bus import EventBus, Event
from .tools.encryption_tool import EncryptionTool
from .tools.email_tool import EmailTool, MockEmailProvider
from .tools.llm_provider import LLMProvider
from .agents.curator_agent import CuratorAgent
from .agents.guardian_agent import GuardianAgent
from .agents.chrono_agent import ChronoAgent
from .agents.messenger_agent import MessengerAgent
from .agents.archivist_agent import ArchivistAgent


class Orchestrator:
    """Coordinates agents and exposes a high‑level API."""

    def __init__(self, db_path: Optional[str] = None, mock_email: bool = True) -> None:
        # Initialise persistence and event bus
        self.db = Database(db_path=db_path)
        self.bus = EventBus(self.db)
        # Configure tools
        self.llm = LLMProvider()
        self.encryption_tool = EncryptionTool()
        # Choose an email provider. Use a mock provider unless
        # explicitly disabled.
        if mock_email:
            email_tool = EmailTool(provider=MockEmailProvider())
        else:
            email_tool = EmailTool()
        self.email_tool = email_tool
        # Instantiate agents
        self.agents = [
            CuratorAgent(self.db, self.llm),
            GuardianAgent(self.db, self.llm, encryption_tool=self.encryption_tool),
            ChronoAgent(self.db, self.llm),
            MessengerAgent(self.db, self.llm, email_tool=self.email_tool),
            ArchivistAgent(self.db, self.llm),
        ]
        # A mapping from event type to agents that care about it for quick dispatch
        self._subscriptions = self._build_subscriptions()

    def _build_subscriptions(self):
        subs = {}
        for agent in self.agents:
            for event_type in getattr(agent, "subscriptions", []):
                subs.setdefault(event_type, []).append(agent)
        return subs

    # ------------------------------------------------------------------
    # Public API used by the CLI
    # ------------------------------------------------------------------

    def create_letter(self, content: str, release_date: str, to_address: str) -> int:
        """Create a new letter and kick off the curation pipeline.

        :returns: The newly created letter's ID.
        """
        letter_id = self.db.insert_letter(
            content=content, release_date=release_date, to_address=to_address, status="draft"
        )
        # Publish the creation event
        self.bus.publish("letter_created", letter_id, payload={})
        # Immediately process events generated by creation
        self.process_events()
        return letter_id

    def schedule_letter(self, letter_id: int, release_date: str) -> None:
        """Update the scheduled release date of an existing letter."""
        # Set or update the release date and status
        self.db.update_letter(letter_id, updates={"release_date": release_date, "status": "scheduled"})
        # Publish an event to indicate scheduling (not required for core flow but useful for extensions)
        self.bus.publish("letter_scheduled", letter_id, payload={"release_date": release_date})
        # Process any immediate reactions
        self.process_events()

    def tick(self) -> None:
        """Advance time in the system.

        A ``tick`` event is published which triggers the Chrono agent to
        evaluate whether any letters are ready for release. Any events
        produced as a result of this evaluation are processed to
        completion before returning.
        """
        # Fire a tick event and dispatch it
        self.bus.publish("tick", None, payload={})
        self.process_events()

    def get_letter(self, letter_id: int):
        """Return a letter record."""
        return self.db.get_letter(letter_id)

    def list_letters(self):
        """List all letters currently in the system."""
        return self.db.list_letters()

    # ------------------------------------------------------------------
    # Internal dispatch logic
    # ------------------------------------------------------------------

    def process_events(self) -> None:
        """Process all queued events until the queue is empty."""
        while True:
            event = self.bus.get_next_event()
            if event is None:
                break
            # Determine which agents subscribe to this event
            subscribers = self._subscriptions.get(event.event_type, [])
            for agent in subscribers:
                agent.handle_event(event, self.bus)
            # If agents published new events during their handling the loop will
            # pick them up on subsequent iterations.
        # After all events are dispatched the queue should be empty.


__all__ = ["Orchestrator"]