"""Chrono Agent – handles temporal reasoning and scheduling.

This agent responds to the ``tick`` event generated by the
orchestrator. On each tick it scans all sealed letters and compares
their release date to the current UTC time. When a letter's
release date has passed, its status is updated to ``ready`` and a
``letter_ready`` event is published.
"""

from __future__ import annotations

from datetime import datetime
from typing import Optional

from .base import BaseAgent
from ..events.event_bus import EventBus, Event


class ChronoAgent(BaseAgent):
    name = "chrono"
    subscriptions = ["tick"]

    def handle_event(self, event: Event, bus: EventBus) -> None:
        # Only process tick events
        if event.event_type != "tick":
            return
        now = datetime.utcnow()
        # Iterate over all letters and check release conditions
        for letter in self.db.list_letters():
            status = letter.get("status")
            if status not in ("sealed", "scheduled"):
                continue
            release_date_str: Optional[str] = letter.get("release_date")
            if not release_date_str:
                # If no release date, treat as immediate
                ready = True
            else:
                try:
                    release_dt = datetime.fromisoformat(release_date_str)
                    ready = release_dt <= now
                except Exception:
                    # Malformed date defaults to immediate
                    ready = True
            if ready:
                # Update status and publish ready event
                self.db.update_letter(letter["id"], updates={"status": "ready"})
                bus.publish("letter_ready", letter["id"], payload={})


__all__ = ["ChronoAgent"]